### ISSUE TITLE
Controller endpoints failing to generate

### ISSUE THREAD

**Issue by guionardo** [ad-on-is/adonis-autoswagger#10]
Using the [example](https://docs.adonisjs.com/guides/controllers#make-controller-command) of Controller in official documentation of AdonisJS, i tried to generate the swagger docs.

The controller has one method:

app/Controllers/Http/PostsController.ts

```js
import { HttpContextContract } from '@ioc:Adonis/Core/HttpContext'

export default class PostsController {
  public async index(_ctx: HttpContextContract) {
    return [
      {
        id: 1,
        title: 'Hello world',
      },
      {
        id: 2,
        title: 'Hello universe',
      },
    ]
  }
}
```

And the routes file has this content

```js
import Route from '@ioc:Adonis/Core/Route'
import AutoSwagger from 'adonis-autoswagger'

// returns swagger in YAML
Route.get('/swagger', async () => {
  return AutoSwagger.docs(Route.toJSON(), {
    path: __dirname,
    title: 'Foo',
    version: '1.0.0',
    tagIndex: 2,
    ignore: ['/swagger', '/docs'],
    common: {
      parameters: {},
      headers: {}, // OpenAPI confomr headers that are commonly used
    },
    snakeCase: true,
  })
})

// Renders Swagger-UI and passes YAML-output of /swagger
Route.get('/docs', async () => {
  return AutoSwagger.ui('/swagger')
})

Route.get('/', async () => {
  return { hello: 'world' }
})
// Route.get('/hc', 'PostsController.index')

// Route.get('/post', 'PostsController.index')
// Route.get('posts', 'PostsController.index')

Route.resource('posts', 'PostsController')
```

package.json

```json
{
  "name": "hello-world",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "node ace serve --watch",
    "build": "node ace build --production",
    "start": "node server.js",
    "lint": "eslint . --ext=.ts",
    "format": "prettier --write ."
  },
  "devDependencies": {
    "@adonisjs/assembler": "^5.4.2",
    "adonis-preset-ts": "^2.1.0",
    "eslint": "^8.11.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-adonis": "^2.1.0",
    "eslint-plugin-prettier": "^4.0.0",
    "pino-pretty": "^7.5.4",
    "prettier": "^2.6.0",
    "typescript": "~4.5",
    "youch": "^3.1.1",
    "youch-terminal": "^2.1.3"
  },
  "dependencies": {
    "@adonisjs/core": "^5.5.3",
    "@adonisjs/repl": "^3.1.9",
    "adonis-autoswagger": "^1.7.5",    
    "proxy-addr": "^2.0.7",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.21"
  }
}
```
Running the project, the endpoints are OK, returning expected responses from requests.
But when I request the swagger file, using the route /docs or /swagger, I get an error in log and a 500 response:

```shell
guionardo @ guio-note ~/dev/lab/adonis/hello-world
└─ $ ▶ node ace serve --watch
[ info ]  building project...
[ info ]  starting http server...
[1647946652482] INFO (hello-world/602887 on guio-note): started server on 0.0.0.0:3333
[ info ]  watching file system for changes
╭─────────────────────────────────────────────────╮
│                                                 │
│    Server address: http://127.0.0.1:3333        │
│    Watching filesystem for changes: YES         │
│                                                 │
╰─────────────────────────────────────────────────╯
[1647946664164] ERROR (hello-world/602887 on guio-note): Cannot read property 'toLowerCase' of undefined
    err: {
      "type": "TypeError",
      "message": "Cannot read property 'toLowerCase' of undefined",
      "stack":
          TypeError: Cannot read property 'toLowerCase' of undefined
              at /home/guionardo/dev/lab/adonis/hello-world/node_modules/adonis-autoswagger/dist/autoswagger.js:285:74
              at Array.forEach (<anonymous>)
              at AutoSwagger.<anonymous> (/home/guionardo/dev/lab/adonis/hello-world/node_modules/adonis-autoswagger/dist/autoswagger.js:228:35)
              at Generator.next (<anonymous>)
              at fulfilled (/home/guionardo/dev/lab/adonis/hello-world/node_modules/adonis-autoswagger/dist/autoswagger.js:5:58)
      "status": 500
    }
```

**Comment by ad-on-is** [comment]
The error in question has to do something with your tags.
Would you mind sharing your config? I assume your `tagIndex: 1` might be wrong

**Comment by ad-on-is** [comment]
Closing since no further response from OP
