### ISSUE TITLE
Can't open swagger.yaml (only in production - after building)

### ISSUE THREAD

**Issue by gabriel-silveira** [ad-on-is/adonis-autoswagger#130]
Hello! I'm using Autoswagger in development and everything is just ok.

But when I build my app for production using the `node ace build` and put it on an EC2 server with a reverse proxy nginx (after using the `node bin/server.js` command) the following error is thrown when trying to access the `/docs`

```
{
  "level": 50,
  "time": 1726928669271,
  "pid": 30702,
  "hostname": "ip-172-31-38-50",
  "request_id": "u6t68ax6zs9bxm6n4parg7r2",
  "err": {
    "type": "Error",
    "message": "ENOENT: no such file or directory, open '/home/ubuntu/app/build/config/../swagger.yml'",
    "stack": "Error: ENOENT: no such file or directory, open '/home/ubuntu/app/build/config/../swagger.yml'\n    at Object.readFileSync (node:fs:448:20)\n    at AutoSwagger.readFile (/home/ubuntu/app/build/node_modules/adonis-autoswagger/dist/autoswagger.js:170:35)\n    at AutoSwagger.docs (/home/ubuntu/app/build/node_modules/adonis-autoswagger/dist/autoswagger.js:179:25)\n    at Object.handler (file:///home/ubuntu/app/build/start/routes.js:8:32)\n    at Runner.<anonymous> (file:///home/ubuntu/app/build/node_modules/@adonisjs/http-server/build/chunk-UQEGDK7Z.js:29:36)\n    at #invokeWithErrorManagement (file:///home/ubuntu/app/build/node_modules/@poppinss/middleware/build/index.js:63:32)\n    at next (file:///home/ubuntu/app/build/node_modules/@poppinss/middleware/build/index.js:11:12)\n    at InitializeAuthMiddleware.handle (file:///home/ubuntu/app/build/node_modules/@adonisjs/auth/build/src/middleware/initialize_auth_middleware.js:11:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "errno": -2,
    "code": "ENOENT",
    "syscall": "open",
    "path": "/home/ubuntu/app/build/config/../swagger.yml",
    "status": 500
  },
  "x-request-id": "u6t68ax6zs9bxm6n4parg7r2",
  "msg": "ENOENT: no such file or directory, open '/home/ubuntu/app/build/config/../swagger.yml'"
}
```

*This error message is displayed on the screen:*

![image](https://github.com/user-attachments/assets/ccaa4b76-a970-4843-8379-0b4b758f0e03)

I have no ideia what could it be...

Any help would be greatly appreciated.

Thank you!

**Comment by Alaa-Ben** [comment]
Hey there !

Have you read and applied the [production-related steps](https://github.com/ad-on-is/adonis-autoswagger?tab=readme-ov-file#production-environment) ?

**Comment by gabriel-silveira** [comment]
> Hey there !
> 
> Have you read and applied the [production-related steps](https://github.com/ad-on-is/adonis-autoswagger?tab=readme-ov-file#production-environment) ?

Oh my gosh! I didn't know about these steps. Thank you, @Alaa-Ben

**Comment by gabriel-silveira** [comment]
Following the steps and applying the changes really solved the problems! Thank you.
