### ISSUE TITLE
Interfaces folder should be optional

### ISSUE THREAD

**Issue by mbombonato** [ad-on-is/adonis-autoswagger#8]
I don't have this folder here and autoswagger return the following error:

```ENOENT: no such file or directory, scandir '/app/app/Interfaces'
err: {
  "type": "Error",
  "message": "ENOENT: no such file or directory, scandir '/app/app/Interfaces'",
  "stack":
      Error: ENOENT: no such file or directory, scandir '/app/app/Interfaces'
          at Object.readdirSync (node:fs:1390:3)
          at AutoSwagger.<anonymous> (/app/node_modules/adonis-autoswagger/dist/autoswagger.js:1158:34)
          at Generator.next (<anonymous>)
          at /app/node_modules/adonis-autoswagger/dist/autoswagger.js:8:71
          at new Promise (<anonymous>)
          at __awaiter (/app/node_modules/adonis-autoswagger/dist/autoswagger.js:4:12)
          at AutoSwagger.getFiles (/app/node_modules/adonis-autoswagger/dist/autoswagger.js:1155:16)
          at AutoSwagger.<anonymous> (/app/node_modules/adonis-autoswagger/dist/autoswagger.js:883:38)
          at Generator.next (<anonymous>)
          at /app/node_modules/adonis-autoswagger/dist/autoswagger.js:8:71
  "errno": -2,
  "syscall": "scandir",
  "code": "ENOENT",
  "path": "/app/app/Interfaces",
  "status": 500
}```

I had to temporary create this folder to keep using it.

**Comment by ad-on-is** [comment]
Oh, thank you... It is fixed now!
